import { useEffect, useMemo, useState } from "react";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "";
const views = {
  overview: "Portfolio overview", explorer: "Policy risk explorer",
  models: "Actuarial vs. ML lab", tail: "Tail-risk lab",
  portfolio: "Portfolio risk", bonus: "Bonus-Malus analysis"
};
const brands = ["B1", "B2", "B3", "B4", "B5", "B6", "B10", "B11", "B12", "B13", "B14"];
const regions = ["R11", "R21", "R22", "R23", "R24", "R25", "R26", "R31", "R41", "R42", "R43", "R52", "R53", "R54", "R72", "R73", "R74", "R82", "R83", "R91", "R93", "R94"];
const initialPolicy = { exposure: 1, area: "D", vehicle_power: 6, vehicle_age: 5, driver_age: 40, bonus_malus: 60, vehicle_brand: "B1", fuel_type: "'Regular'", density: 500, region: "R11" };

async function api(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  if (!response.ok) { const body = await response.json(); throw new Error(body.detail || `Request failed (${response.status})`); }
  return response.json();
}
const money = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value ?? 0);
const number = value => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value ?? 0);
const pct = value => `${number((value ?? 0) * 100)}%`;

function Metrics({ items }) { return <div className="metric-grid">{items.map(([label, value, note]) => <article className="metric" key={label}><small>{label}</small><strong>{value}</strong>{note && <em>{note}</em>}</article>)}</div>; }
function Bars({ rows, label, value, format = number }) {
  const max = Math.max(...rows.map(row => Number(row[value]) || 0), 1);
  return <div className="bars horizontal">{rows.map((row, index) => <div className="bar-row" key={`${row[label]}-${index}`}><span>{row[label]}</span><div className="bar-track"><div className="bar-fill" style={{ width: `${100 * Number(row[value]) / max}%` }} /></div><strong>{format(row[value])}</strong></div>)}</div>;
}
function DataTable({ rows, columns }) { return <div className="table-wrap"><table><thead><tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map(([key, label, format]) => <td key={label}>{format ? format(row[key]) : row[key] ?? "—"}</td>)}</tr>)}</tbody></table></div>; }

function Overview({ data }) {
  if (!data) return <p>Loading portfolio evidence…</p>;
  const { portfolio: p, severity: s, loss_concentration: concentration } = data;
  const rows = concentration.map(row => ({ label: `Top ${number(row.TopClaimShare * 100)}%`, value: row.LossShare }));
  return <><Metrics items={[["Policies", number(p.policies), "earned exposures"], ["Recorded claims", number(p.recorded_claims), "frequency target"], ["Total exposure", number(p.exposure), "policy-years"], ["Total linked loss", money(p.linked_loss), "severity records"], ["Claim frequency", number(p.frequency), "per policy-year"], ["Mean severity", money(s.mean), "conditional on claim"], ["Pure premium", money(p.linked_loss / p.exposure), "loss per exposure"], ["Largest claim", money(s.maximum), "observed maximum"]]} /><div className="panel-grid"><article className="panel wide"><PanelTitle eyebrow="Loss structure" title="Tail concentration" /><Bars rows={rows} label="label" value="value" format={pct} /></article><article className="panel insight"><p className="eyebrow">Portfolio signal</p><h2>Why the tail matters</h2><p>The largest 1% of linked claims produces {pct(concentration.find(row => row.TopClaimShare === 0.01)?.LossShare)} of loss. ClaimGuard therefore separates expected loss from tail scenarios.</p></article></div></>;
}
function PanelTitle({ eyebrow, title, children }) { return <div className="panel-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children}</div>; }

function PolicyExplorer() {
  const [policy, setPolicy] = useState(initialPolicy); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = event => setPolicy(current => ({ ...current, [event.target.name]: event.target.type === "number" ? Number(event.target.value) : event.target.value }));
  const submit = async event => { event.preventDefault(); setLoading(true); setError(""); try { setResult(await api("/policy/score", { method: "POST", body: JSON.stringify(policy) })); } catch (reason) { setError(reason.message); } finally { setLoading(false); } };
  return <div className="explorer-grid"><form className="panel form-panel" onSubmit={submit}><PanelTitle eyebrow="Policy features" title="Estimate risk" /><div className="form-grid">
    <Field label="Exposure"><input name="exposure" type="number" min="0.01" max="1" value={policy.exposure} onChange={update} /></Field>
    <Field label="Area"><select name="area" value={policy.area} onChange={update}>{["A","B","C","D","E","F"].map(x => <option key={x}>{x}</option>)}</select></Field>
    {[['vehicle_power','Vehicle power'],['vehicle_age','Vehicle age'],['driver_age','Driver age'],['bonus_malus','Bonus-Malus']].map(([name,label]) => <Field label={label} key={name}><input name={name} type="number" min="0" value={policy[name]} onChange={update} /></Field>)}
    <Field label="Vehicle brand"><select name="vehicle_brand" value={policy.vehicle_brand} onChange={update}>{brands.map(x => <option key={x}>{x}</option>)}</select></Field>
    <Field label="Fuel"><select name="fuel_type" value={policy.fuel_type} onChange={update}><option value="'Diesel'">Diesel</option><option value="'Regular'">Regular</option></select></Field>
    <Field label="Density"><input name="density" type="number" min="0" value={policy.density} onChange={update} /></Field>
    <Field label="Region"><select name="region" value={policy.region} onChange={update}>{regions.map(x => <option key={x}>{x}</option>)}</select></Field>
  </div><button className="primary" disabled={loading}>{loading ? "Scoring…" : "Score policy"}<span>→</span></button><p className="error" role="alert">{error}</p></form><article className="panel result-panel">{result ? <RiskResult result={result} /> : <div className="empty"><div className="radar-mark">CG</div><h2>Ready to assess</h2><p>Enter policy characteristics to generate a complete risk profile.</p></div>}</article></div>;
}
function Field({ label, children }) { return <label>{label}{children}</label>; }
function RiskResult({ result: r }) { return <><div className="score-head"><div><p className="eyebrow">ClaimGuard score</p><div className="score-number">{number(r.claimguard_score)}</div></div><span className="pill">{r.overall_risk} RISK</span></div><h2>{r.risk_segment}</h2><div className="flow"><div><small>Frequency</small><strong>{number(r.expected_claims_per_year)}</strong></div><div><small>Severity</small><strong>{money(r.expected_claim_severity)}</strong></div><div><small>Annual loss</small><strong>{money(r.expected_annual_loss)}</strong></div><div><small>Tail risk</small><strong>{pct(r.large_loss_probability)}</strong></div></div><div className="risk-lines"><div className="risk-line"><span>Exposure-period loss</span><strong>{money(r.expected_loss_for_exposure)}</strong></div><div className="risk-line"><span>Tail percentile</span><strong>{number(r.tail_risk_percentile)}th</strong></div><div className="risk-line"><span>Frequency / severity</span><strong>{r.frequency_risk} / {r.severity_risk}</strong></div></div><div className="drivers">{r.primary_risk_drivers.map(driver => <span key={driver}>{driver}</span>)}</div></>; }

function Models({ benchmark, deciles }) {
  const tasks = useMemo(() => [...new Set(benchmark.map(row => row.Task))], [benchmark]); const [task, setTask] = useState(""); const [model, setModel] = useState("tweedie"); const selectedTask = task || tasks[0];
  return <><article className="panel"><PanelTitle eyebrow="Common holdouts" title="Model benchmark"><select value={selectedTask} onChange={e => setTask(e.target.value)}>{tasks.map(x => <option key={x}>{x}</option>)}</select></PanelTitle><DataTable rows={benchmark.filter(row => row.Task === selectedTask)} columns={[["Metric","Metric"],["TraditionalModel","Traditional model"],["TraditionalValue","Value",number],["MLModel","ML model"],["MLValue","Value",number],["Winner","Winner"]]} /></article><article className="panel"><PanelTitle eyebrow="Risk ordering" title="Observed loss by predicted decile"><select value={model} onChange={e => setModel(e.target.value)}><option value="tweedie">Tweedie GLM</option><option value="gbm_component">GBM components</option><option value="direct_boosting">Direct boosting</option><option value="poisson_gamma">Poisson × Gamma</option></select></PanelTitle><Bars rows={deciles[model] || []} label="RiskDecile" value="ObservedLossCost" format={money} /></article></>;
}
function Tail({ data, quantiles }) { if (!data) return null; const g = data.gpd; return <><Metrics items={[["EVT threshold",money(g.threshold),`${number(g.exceedances)} exceedances`],["Tail probability",pct(g.exceedance_probability),"above threshold"],["GPD shape",number(g.shape),g.finite_variance ? "finite variance":"infinite fitted variance"],["Expected tail claim",money(g.expected_claim_given_exceedance),"conditional exceedance"]]} /><div className="panel-grid"><article className="panel wide"><PanelTitle eyebrow="Distribution comparison" title="Extreme severity quantiles" /><DataTable rows={quantiles} columns={[["Probability","Quantile",pct],["Empirical","Empirical",money],["Gamma","Gamma",money],["Lognormal","Lognormal",money],["EVT","EVT",money]]} /></article><article className="panel insight"><p className="eyebrow">Peaks over threshold</p><h2>GPD diagnosis</h2><div id="gpd-details">{[["Shape",number(g.shape)],["Scale",money(g.scale)],["Mean finite",g.finite_mean ? "Yes":"No"],["Variance finite",g.finite_variance ? "Yes":"No"]].map(([a,b]) => <div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></article></div></>;
}
function Portfolio({ stress, segments }) { if (!stress) return null; const full = stress.full_tail; return <><Metrics items={[["Expected aggregate loss",money(full.mean),`${number(stress.simulations)} simulations`],["95% VaR",money(full.var_95),"annual aggregate"],["99% VaR",money(full.var_99),"annual aggregate"],["99% expected shortfall",money(full.expected_shortfall_99),"tail average"]]} /><article className="panel"><PanelTitle eyebrow="Frequency × severity" title="Policy risk segments" /><DataTable rows={segments} columns={[["RiskSegment","Segment"],["Policies","Policies",number],["PredictedAnnualFrequency","Frequency",number],["ExpectedSeverity","Severity",money],["AnnualPurePremium","Pure premium",money],["LargeLossProbability","Tail probability",pct],["ObservedLossCost","Observed loss cost",money]]} /></article></>; }
function Bonus({ metrics, observed }) { if (!metrics) return null; const sample = observed.filter((_, index) => index % Math.max(1, Math.floor(observed.length / 15)) === 0); return <><article className="panel"><PanelTitle eyebrow="Experience rating" title="Observed risk by Bonus-Malus" /><Bars rows={sample} label="BonusMalusBand" value="PurePremium" format={money} /></article><article className="panel insight full"><p className="eyebrow">Interpretation</p><h2>Does the system separate risk?</h2><p>A 10-point increase corresponds to a {number((metrics.frequency.relativity_per_10_points - 1) * 100)}% modeled frequency relativity. The relationship is predictive rather than causal.</p></article></>; }

export default function App() {
  const [view, setView] = useState("overview"); const [online, setOnline] = useState(false); const [data, setData] = useState({ benchmark: [], deciles: {}, quantiles: [], segments: [], bonusObserved: [] }); const [error, setError] = useState("");
  useEffect(() => { let active = true; Promise.all([api("/health"),api("/portfolio/summary"),api("/models/benchmark"),api("/portfolio/risk-deciles"),api("/tail-risk"),api("/tail-risk/quantiles"),api("/portfolio/stress-test"),api("/portfolio/segments"),api("/bonus-malus"),api("/bonus-malus/observed")]).then(([,overview,benchmark,deciles,tail,quantiles,stress,segments,bonus,bonusObserved]) => { if (active) { setOnline(true); setData({ overview, benchmark, deciles, tail, quantiles, stress, segments, bonus, bonusObserved }); } }).catch(reason => active && setError(reason.message)); return () => { active = false; }; }, []);
  return <><aside className="sidebar"><a className="brand" href="#overview"><span>CG</span><strong>ClaimGuard</strong></a><p className="eyebrow">Motor TPL intelligence</p><nav aria-label="Dashboard views">{Object.entries(views).map(([key,label]) => <button key={key} className={`nav-item ${view === key ? "active":""}`} onClick={() => setView(key)}>{label}</button>)}</nav><div className={`status ${online ? "online":""}`}><i /><span>{online ? "Models online" : error || "Connecting"}</span></div></aside><main><header><div><p className="eyebrow">Research dashboard</p><h1>{views[view]}</h1></div><div className="data-badge">freMTPL2 · France</div></header><section className="view active">{view === "overview" && <Overview data={data.overview} />}{view === "explorer" && <PolicyExplorer />}{view === "models" && <Models benchmark={data.benchmark} deciles={data.deciles} />}{view === "tail" && <Tail data={data.tail} quantiles={data.quantiles} />}{view === "portfolio" && <Portfolio stress={data.stress} segments={data.segments} />}{view === "bonus" && <Bonus metrics={data.bonus} observed={data.bonusObserved} />}</section></main></>;
}
